services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./custom_components:/app/custom_components
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app
